name: Run DBT Core

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow
  workflow_dispatch: # Enables manual triggering

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Specify the Python version compatible with DBT

    # Step 3: Install dependencies
    - name: Install DBT Core
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-[YOUR_ADAPTER] # Replace [YOUR_ADAPTER] with e.g., snowflake, bigquery, redshift, etc.

    # Step 4: Set up DBT profiles.yml
    - name: Set up DBT profiles.yml
      run: |
        mkdir -p ~/.dbt
        echo "${{ secrets.PROFILES_YML }}" > ~/.dbt/profiles.yml

    # Step 5: Run DBT commands
    - name: Run DBT models
      env:
        DBT_DATABASE_URL: ${{ secrets.DBT_DATABASE_URL }}  # Add environment variables as needed
      run: |
        dbt debug  # Optional: Validate DBT setup
        dbt deps   # Install packages
        dbt run    # Run models
        dbt test   # Run tests
