name: Run dbt Job on Snowflake

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dbt and Snowflake adapter
      - name: Install dbt and Snowflake adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      # Step 4: Create profiles directory if it doesn't exist
      - name: Create .dbt directory and configure credentials
        run: |
          mkdir -p ~/.dbt  # Create .dbt directory if it doesn't exist
          echo "-- This is a generated profiles.yml file" > ~/.dbt/profiles.yml
          echo "snowflake:" >> ~/.dbt/profiles.yml
          echo "  target: dev" >> ~/.dbt/profiles.yml
          echo "  outputs:" >> ~/.dbt/profiles.yml
          echo "    dev:" >> ~/.dbt/profiles.yml
          echo "      type: snowflake" >> ~/.dbt/profiles.yml
          echo "      account: ${{ secrets.SNOWFLAKE_ACCOUNT }}" >> ~/.dbt/profiles.yml
          echo "      user: ${{ secrets.SNOWFLAKE_USER }}" >> ~/.dbt/profiles.yml
          echo "      password: ${{ secrets.SNOWFLAKE_PASSWORD }}" >> ~/.dbt/profiles.yml
          echo "      role: ${{ secrets.SNOWFLAKE_ROLE }}" >> ~/.dbt/profiles.yml
          echo "      warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> ~/.dbt/profiles.yml
          echo "      database: ${{ secrets.SNOWFLAKE_DATABASE }}" >> ~/.dbt/profiles.yml
          echo "      schema: ${{ secrets.SNOWFLAKE_SCHEMA }}" >> ~/.dbt/profiles.yml
          echo "      threads: 4" >> ~/.dbt/profiles.yml

      # Step 5: Run dbt commands
      - name: Run dbt commands
        run: |
          dbt debug    # Check if the connection works
          dbt deps     # Install dbt dependencies
          dbt run      # Run dbt models
          dbt test     # Optionally run dbt tests
