name: Run dbt Job on Snowflake

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Step 3: Install dbt and Snowflake adapter
      - name: Install dbt and Snowflake adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      # Step 4: Set Snowflake environment variables
      - name: Set Snowflake credentials
        run: |
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_WAREHOUSE=${{ secrets.SNOWFLAKE_WAREHOUSE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_DATABASE=${{ secrets.SNOWFLAKE_DATABASE }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_SCHEMA=${{ secrets.SNOWFLAKE_SCHEMA }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_THREADS=4" >> $GITHUB_ENV

      # Step 5: Run dbt commands without --profiles-dir
      - name: Run dbt commands
        run: |
          dbt run -h
